### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by rollsthomas** [kentcdodds/advanced-react-patterns-v2#34] opened 2018-05-24 20:55 UTC
I also ran the npm run setup command separately and it get the same error on npm run build. 

I followed the instructions on the error message, but no dice. 

In step 3, it says remove webpack, but there is no webpack on package.json.
I reran the command with yarn, but got the same error. 

The error message also says to add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
Couldn't find any .env file.

Thanks for the help

```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "webpack": "3.10.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of webpack was detected higher up in the tree:

  /Users/home/node_modules/webpack (version: 4.6.0) 

Manually installing incompatible versions is known to cause hard-to-debug issues.
To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.

  2. Delete node_modules in your project folder.

  3. Remove "webpack" from dependencies and/or devDependencies in the package.json file in your project folder.

  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if /Users/home/node_modules/webpack is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls webpack in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed webpack.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.
```

**Comment by kentcdodds** [comment] 2018-05-24 21:14
I'm pretty sure the problem is that you have webpack installed in `/Users/home/node_modules`. I'm guessing that's by error, and you should probably remove the `/Users/home/node_modules` directory.

I'm going to close this issue, but feel free to comment if you have further questions.

**Comment by kentcdodds** [comment] 2018-05-24 21:15
I should probably add that this is actually a react-scripts bug. You might consider reporting it there: https://github.com/facebook/create-react-app/issues/new

Good luck!

**Closed by kentcdodds** 2018-05-24 21:14 UTC

**Comment by rollsthomas** [comment] 2018-05-25 11:57
Thanks! I deleted the node_modules dir as you said and it worked perfectly.

**Comment by tomluo5** [comment] 2018-10-31 15:51
Thanks, I deleted the node_modoles after success!

**Comment by marvidac** [comment] 2019-04-25 12:15
For me, delete the node_modules didn't work. So I had to put "SKIP_PREFLIGHT_CHECK=true" in the '.env'.

**Comment by yairEO** [comment] 2019-05-30 09:07
I have the same issue:

```
▶ npm ls webpack 
foo@1.0.0 /Users/yeven/projects/foo
├─┬ @storybook/react@5.0.11
│ ├─┬ @storybook/core@5.0.11
│ │ └── webpack@4.32.2  deduped
│ └── webpack@4.32.2 
└─┬ react-scripts@3.0.1
  └── webpack@4.29.6 
```

**Comment by chadacious** [comment] 2019-06-03 19:59
I had the same issue as yairEO where I was using several linked react-app libraries. I was able to resolve it by deleting all my project node_modules (and the symlink directories in my %AppData%\npm\node_modules).

**Comment by rmille4612** [comment] 2019-06-23 06:50
I first globally uninstalled webpack (npm uninstall -g webpack) and then globally reinstalled webpack 4.29.6 (npm install -g webpack@4.29.6).  Next I deleted any node module which started with the word webpack in the directory C:\Users\MyUserName\node_modules folder but left all other packages untouched.  This corrected to issue.  I still have webpack installed in my AppData folder and in the programs folder.  Using Windows 10, node 10.16.0, npm 6.9.0.  Just a slight tweek on the answer given above.  I spent three days on this issue so I hope it helps!

**Comment by unnatikala05** [comment] 2019-09-10 06:08
i have executed all the steps but none worked for me

**Comment by rmille4612** [comment] 2019-09-15 22:50
unnatikala05.... react is very moody.  Doesn't seem to matter whether you're install on Mac, Windows or whatever.  I've found you usually have some configuration tweaking to do after you first install it.  Also, Facebook is constantly providing updates for newer versions of react.  When you run npm create-react-app or npm init react-app you are installing dependencies from online repositories.  If an update was placed there which incompatible with your installed libraries you'll need update your version npm.  If your using windows that will likely mean literally removing and reinstalling the new version of NodJS from their website.  Debugging can be frustrating at best.  If you can provide more information about what errors you're receiving, and what code your running, I can try to help.  Is it the same code in this repository? Or from another?

**Comment by ModybinYunus** [comment] 2019-11-30 07:55
You can try this also it's worked for me 
go to your package.json
replace "react-scripts": "whatever ver u got" to "react-scripts": "1.1.4",
then run npm install, after that npm start

**Comment by sounakbh** [comment] 2019-12-07 18:33
Thank you! Worked for me too.

**Comment by esdrasdemorais** [comment] 2020-01-05 18:20
- Remove node-module, package-lock.json;
- Check for the latest version and change if necessary;
- npm install;

**Comment by katarisrividya** [comment] 2020-04-05 10:27
> You can try this also it's worked for me
>delete node-modules
>delete package-lock.json
> go to your package.json
> replace "react-scripts": "whatever ver u got" to "react-scripts": "1.1.4",
> then run npm install, after that npm start

Thank you!I have been working on this for 2 days finally I got it

**Comment by dzenanvelic** [comment] 2020-09-17 15:51
Hello!!!
 Last one is worked for me too: 

 delete node-modules
delete package-lock.json
go to your package.json
replace "react-scripts": "whatever  u got" to "react-scripts": "1.1.4",
then run npm install, after that npm start

Thanks for a tip.

**Comment by ericerodgers** [comment] 2020-09-28 21:29
Worked for me too! Was preventing from starting Wes Bos's React For Beginner's course for over a day now... Thanks! ModybinYunus!

delete node-modules
delete package-lock.json
go to your package.json
replace "react-scripts": "whatever u got" to "react-scripts": "1.1.4",
then run npm install, after that npm start

**Comment by Prabhakar-Nagaraj** [comment] 2020-10-09 14:41
> > You can try this also it's worked for me
> > delete node-modules
> > delete package-lock.json
> > go to your package.json
> > replace "react-scripts": "whatever ver u got" to "react-scripts": "1.1.4",
> > then run npm install, after that npm start
> 
> Thank you!I have been working on this for 2 days finally I got it

thanks it worked

**Comment by saurabhyadavz** [comment] 2021-02-21 14:29
> > > You can try this also it's worked for me
> > > delete node-modules
> > > delete package-lock.json
> > > go to your package.json
> > > replace "react-scripts": "whatever ver u got" to "react-scripts": "1.1.4",
> > > then run npm install, after that npm start
> > 
> > 
> > Thank you!I have been working on this for 2 days finally I got it
> 
> thanks it worked

Thanks, I was stuck for the last 3 hours. :)
